### ISSUE TITLE
Database architecture

### ISSUE THREAD

**Issue by V8-Luky** [V8-Luky/dspro1#12]
Vector databases to store the embeddings?

**Comment by V8-Luky** [comment]
Azure: https://learn.microsoft.com/en-us/azure/cosmos-db/vector-database
Other: https://www.datacamp.com/blog/the-top-5-vector-databases
https://www.graft.com/blog/top-open-source-vector-databases

Chroma?

**Comment by SilvanHSLU** [comment]
@V8-Luky ChatGPT always comes with https://www.pinecone.io/, have you checked this or may you take a short look?

**Comment by V8-Luky** [comment]
@SilvanHSLU - haven't checked that yet, seems very interesting and applicable to ouir case though - thanks for the input :)
